# Use R language
language: r
addons:
  apt:
    packages:
    - "python3"
#Define multiple R-versions, one from bioconductor
r:
  - oldrel
  - release
  - devel
  - bioc-devel
# Set one of you dependencies from github
r_github_packages: 
  - r-lib/testthat
  - r-lib/covr
  - r-lib/pkgdown
# set a Linux system dependency
apt_packages:
  - libxml2-dev
