# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install linux prerequesites
        run: |
          sudo apt-get install libxml2-dev
      - name: Install dependencies I
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          reticulate::install_miniconda(update = TRUE)
          reticulate::conda_create('r-reticulate', packages = c('python==3.6.9'))
          keras::install_keras(tensorflow = "2.0", extra_packages = c('IPython', 'requests', 'certifi', 'urllib3', 'six', 'tensorflow_probability==0.8.0'))
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "error")
        shell: Rscript {0}
